# Descriptive Statistics

## Data Summarization (counts, proportion, percentage, and cumulative of all)

In [12]:
!pip install numpy pandas matplotlib openpyxl --quiet

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

In [6]:
# Importing libraries
import numpy as np
import pandas as pd

In [15]:
df = pd.read_excel('../data/CDAC_DataBook.xlsx', sheet_name='ERPData')
df.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [18]:
# Extracting one columns from dataset
x1 = df.MaterialID
x1.head()

0    TMI-43T
1    AXCP-78
2    LXCV-21
3    AXCP-78
4    AXCP-78
Name: MaterialID, dtype: str

In [23]:
# length of unique materialid
len(np.unique(x1))

6

In [21]:
np.unique(x1, return_counts=True)

(array(['AXCP-78', 'DDBN-89', 'GCVB-79', 'LXCV-21', 'SDRT-67', 'TMI-43T'],
       dtype=object),
 array([11,  8,  5,  5,  6, 15]))

In [24]:
# Counting the number of unique material ids
x1.value_counts()

MaterialID
TMI-43T    15
AXCP-78    11
DDBN-89     8
SDRT-67     6
LXCV-21     5
GCVB-79     5
Name: count, dtype: int64

In [25]:
# Converting label (materialid) into a column using reset_index()
df1 = x1.value_counts().reset_index()
df1

  MaterialID  count
0    TMI-43T     15
1    AXCP-78     11
2    DDBN-89      8
3    SDRT-67      6
4    LXCV-21      5
5    GCVB-79      5

In [26]:
# Proportion of each material id
df1['prop'] = df1['count']/sum(df1['count'])
df1

  MaterialID  count  prop
0    TMI-43T     15  0.30
1    AXCP-78     11  0.22
2    DDBN-89      8  0.16
3    SDRT-67      6  0.12
4    LXCV-21      5  0.10
5    GCVB-79      5  0.10

In [28]:
# Percentate proportion of each material id
df1['pct'] = df1['prop']*100
df1

  MaterialID  count  prop   pct
0    TMI-43T     15  0.30  30.0
1    AXCP-78     11  0.22  22.0
2    DDBN-89      8  0.16  16.0
3    SDRT-67      6  0.12  12.0
4    LXCV-21      5  0.10  10.0
5    GCVB-79      5  0.10  10.0

In [29]:
# Cumulative percentage for each material id
df1['Cumpct'] = np.cumsum(df1['pct'])
df1

  MaterialID  count  prop   pct  Cumpct
0    TMI-43T     15  0.30  30.0    30.0
1    AXCP-78     11  0.22  22.0    52.0
2    DDBN-89      8  0.16  16.0    68.0
3    SDRT-67      6  0.12  12.0    80.0
4    LXCV-21      5  0.10  10.0    90.0
5    GCVB-79      5  0.10  10.0   100.0

In [30]:
# Sorting the material id based on count
df1.sort_values('count',ascending=False)

  MaterialID  count  prop   pct  Cumpct
0    TMI-43T     15  0.30  30.0    30.0
1    AXCP-78     11  0.22  22.0    52.0
2    DDBN-89      8  0.16  16.0    68.0
3    SDRT-67      6  0.12  12.0    80.0
4    LXCV-21      5  0.10  10.0    90.0
5    GCVB-79      5  0.10  10.0   100.0