In [ ]:
import pandas as pd

In [ ]:
# Series
x1 = [1,2,3,4,5]

In [ ]:
type(x1)

list

In [ ]:
s1 = pd.Series(x1, index=["row1","row2","row3","row4","row5"])

In [ ]:
s1

row1    1
row2    2
row3    3
row4    4
row5    5
dtype: int64

In [ ]:
s1.iloc[2]

np.int64(3)

In [ ]:
s1.loc["row3"]

np.int64(3)

In [ ]:
s2 = pd.Series([1,2,3,4,5], index=["A","A","B","A","B"])

In [ ]:
s2.loc["A"]

A    1
A    2
A    4
dtype: int64

In [ ]:
s1

row1    1
row2    2
row3    3
row4    4
row5    5
dtype: int64

In [ ]:
s3 = pd.Series([3,9], index=["row2","row7"])

In [ ]:
s1 = pd.concat([s1,s3])

In [ ]:
s1

row1    1
row2    2
row3    3
row4    4
row5    7
row6    3
row7    9
row2    3
row7    9
dtype: int64

In [ ]:
len(s1)

7

In [ ]:
s1.iloc[4] = 7

In [ ]:
s1.iloc[4]

row2    7
row2    7
dtype: int64

In [ ]:
s1.loc["row2"] = 7

In [ ]:
s1

row1    1
row2    7
row3    3
row4    4
row5    7
row6    3
row7    9
row2    7
row7    9
dtype: int64

In [ ]:
s1.drop(["row2","row7"])

row1    1
row3    3
row4    4
row5    7
row6    3
dtype: int64

In [ ]:
s1.drop(s1.index[2])

row1    1
row2    7
row4    4
row5    7
row6    3
row7    9
row2    7
row7    9
dtype: int64

In [ ]:
s4 = pd.Series([2,3,2,2,4,4,3,4,4,4,4,5,5,2,4,5])

In [ ]:
s4_counts=s4.value_counts()

In [ ]:
s4_counts

4    7
2    4
5    3
3    2
Name: count, dtype: int64

In [ ]:
s1

row1    1
row2    7
row3    3
row4    4
row5    7
row6    3
row7    9
row2    7
row7    9
dtype: int64

In [ ]:
import numpy as np

In [ ]:
np.where(s1==7)

(array([1, 4, 7]),)

In [ ]:
s1.index[np.where(s1==9)[0]]

Index(['row7', 'row7'], dtype='object')

In [ ]:
a1 = np.array([3,5,4,3,3,3,7,8,9])

In [ ]:
len(np.where(a1==3))

1

In [ ]:
len(np.where(a1==3)[0])

4

In [ ]:
# Data Frame
df = pd.DataFrame([['A',1234,20000],['B',5678,10000],['C',1357,80000],['D',4567,30000]], columns=["Name","Account_number","Account_Balance"])

In [ ]:
df

  Name  Account_number  Account_Balance
0    A            1234            20000
1    B            5678            10000
2    C            1357            80000
3    D            4567            30000

In [ ]:
df1 = df.iloc[[1,2]].reset_index(drop=True)

In [ ]:
df1

  Name  Account_number  Account_Balance
0    B            5678            10000
1    C            1357            80000

In [ ]:
df1.iloc[1]

index                  2
Name                   C
Account_number      1357
Account_Balance    80000
Name: 2, dtype: object

In [ ]:
x1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])

In [ ]:
# Dictionary

In [ ]:
stu_info = {"Name":['A','B','C','D'],"Roll_no":[1,2,3,4],"Marks":[50,60,75,64]}

In [ ]:
df = pd.DataFrame(stu_info)

In [ ]:
df

  Name  Roll_no  Marks
0    A        1     50
1    B        2     60
2    C        3     75
3    D        4     64

In [ ]:
newdf=pd.DataFrame([['E',7,80],['F',10,65]], columns=df.columns)

In [ ]:
newdf

  Name  Roll_no  Marks
0    E        7     80
1    F       10     65

In [ ]:
df2=pd.concat([df,newdf]).reset_index(drop=True)

In [ ]:
df2

  Name  Roll_no  Marks
0    A        1     50
1    B        2     60
2    C        3     75
3    D        4     64
4    E        7     80
5    F       10     65

In [ ]:
x1 = [67,89,75,62,59,82]

In [ ]:
df2["Marks2"] = x1

In [ ]:
df2

  Name  Roll_no  Marks  Marks2
0    A        1     50      67
1    B        2     60      89
2    C        3     75      75
3    D        4     64      62
4    E        7     80      59
5    F       10     65      82

In [ ]:
df2.shape

(6, 4)

In [ ]:
df2.at[3,'Marks']

np.int64(64)

In [ ]:
df2.at[3,'Marks'] = 74

In [ ]:
df2

  Name  Roll_no  Marks  Marks2
0    A        1     50      67
1    B        2     60      89
2    C        3     75      75
3    D        4     74      62
4    E        7     80      59
5    F       10     65      82

In [ ]:
df3 = df2.iloc[[0,3,5]].reset_index(drop=True)

In [ ]:
df3

  Name  Roll_no  Marks  Marks2
0    A        1     50      67
1    D        4     74      62
2    F       10     65      82

In [ ]:
mySubject = df2[["Name","Marks2"]]
mySubject

  Name  Marks2
0    A      67
1    B      89
2    C      75
3    D      62
4    E      59
5    F      82

In [ ]:
df2.iloc[:,[1,2]]

   Roll_no  Marks
0        1     50
1        2     60
2        3     75
3        4     74
4        7     80
5       10     65

In [ ]:
df2.drop([0,5],axis=0)

  Name  Roll_no  Marks  Marks2
1    B        2     60      89
2    C        3     75      75
3    D        4     74      62
4    E        7     80      59

In [ ]:
df2.drop(["Roll_no","Marks"], axis=1)

  Name  Marks2
0    A      67
1    B      89
2    C      75
3    D      62
4    E      59
5    F      82

In [ ]:
import os

In [ ]:
os.getcwd()

'/content'

In [ ]:
os.chdir("/content/drive/MyDrive/CDAC_2026/AAS")

In [ ]:
dataset = pd.read_excel("CDAC_DataBook.xlsx",sheet_name='ERPData')

In [ ]:
dataset

   MaterialID Location  Quantity
0     TMI-43T    MWH-4        34
1     AXCP-78    MWH-1        67
2     LXCV-21    MWH-2        27
3     AXCP-78    MWH-5        65
4     AXCP-78    MWH-4        36
5     TMI-43T    MWH-4        78
6     TMI-43T    MWH-4        31
7     TMI-43T    MWH-2        29
8     GCVB-79    MWH-2        10
9     TMI-43T    MWH-1       120
10    SDRT-67    MWH-1        34
11    SDRT-67    MWH-4        58
12    TMI-43T    MWH-4        76
13    TMI-43T    MWH-4        32
14    TMI-43T    MWH-3        65
15    GCVB-79    MWH-2        87
16    SDRT-67    MWH-5        12
17    SDRT-67    MWH-5       102
18    TMI-43T    MWH-4        34
19    TMI-43T    MWH-4        52
20    TMI-43T    MWH-4        39
21    TMI-43T    MWH-4        75
22    DDBN-89    MWH-4        48
23    DDBN-89    MWH-5        71
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
26    DDBN-89    MWH-1        57
27    LXCV-21    MWH-5        83
28    LXCV-21    MWH-5        34
29    LXCV-21    MWH-5        57
30    DDBN-89    MWH-4        27
31    TMI-43T    MWH-4        65
32    TMI-43T    MWH-4        43
33    TMI-43T    MWH-5       112
34    GCVB-79    MWH-5        26
35    GCVB-79    MWH-2        31
36    GCVB-79    MWH-2        28
37    AXCP-78    MWH-5        65
38    AXCP-78    MWH-5        70
39    AXCP-78    MWH-1       145
40    DDBN-89    MWH-1        34
41    SDRT-67    MWH-1        57
42    SDRT-67    MWH-2        31
43    DDBN-89    MWH-3        38
44    LXCV-21    MWH-3        42
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85
47    AXCP-78    MWH-3        29
48    AXCP-78    MWH-1        75
49    DDBN-89    MWH-1        39

In [ ]:
dataset.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [ ]:
dataset.shape

(50, 3)